development:
  adapter: postgresql
  encoding: utf8
  database: tinboard
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: tinboard
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: tinboard_production
  pool: 5
  username:
  password:
